// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicDB;

#nullable disable

namespace MusicDB.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260419220158_isactive")]
    partial class isactive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MusicModels.Chord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("IndexInLine")
                        .HasColumnType("int");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<int?>("Spaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("Degree")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tips")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UtubLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scale")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicModels.SongRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("FulfillerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("bit");

                    b.Property<double?>("PriorityScore")
                        .HasColumnType("float");

                    b.Property<string>("SongDes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("FulfillerId");

                    b.ToTable("SongRequests");
                });

            modelBuilder.Entity("MusicModels.SongRequestVote", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SongRequestId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.HasKey("UserId", "SongRequestId");

                    b.HasIndex("SongRequestId");

                    b.ToTable("songRequestVotes");
                });

            modelBuilder.Entity("MusicModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("srcImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicModels.UserFavoriteSong", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("UserFavoriteSongs");
                });

            modelBuilder.Entity("MusicModels.WordLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("WordLines");
                });

            modelBuilder.Entity("MusicModels.Chord", b =>
                {
                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("Chords")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.HasOne("MusicModels.Category", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.User", "User")
                        .WithMany("MySongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.SongRequest", b =>
                {
                    b.HasOne("MusicModels.User", "User")
                        .WithMany("SongRequests")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.User", "Fulfiller")
                        .WithMany("FulfilledRequests")
                        .HasForeignKey("FulfillerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Fulfiller");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.SongRequestVote", b =>
                {
                    b.HasOne("MusicModels.SongRequest", "SongRequest")
                        .WithMany("Votes")
                        .HasForeignKey("SongRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.User", "User")
                        .WithMany("SongVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SongRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.UserFavoriteSong", b =>
                {
                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.User", "User")
                        .WithMany("FavoriteSongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.WordLine", b =>
                {
                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("WordLines")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicModels.Category", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.Navigation("Chords");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("WordLines");
                });

            modelBuilder.Entity("MusicModels.SongRequest", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("MusicModels.User", b =>
                {
                    b.Navigation("FavoriteSongs");

                    b.Navigation("FulfilledRequests");

                    b.Navigation("MySongs");

                    b.Navigation("SongRequests");

                    b.Navigation("SongVotes");
                });
#pragma warning restore 612, 618
        }
    }
}
