// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicDB;

#nullable disable

namespace MusicDB.Migrations
{
    [DbContext(typeof(DataBase))]
    [Migration("20260203120408_add-pass")]
    partial class addpass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MusicModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MusicModels.Chord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Degree")
                        .HasColumnType("int");

                    b.Property<int?>("IndexInLine")
                        .HasColumnType("int");

                    b.Property<int?>("LineNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScaleId")
                        .HasColumnType("int");

                    b.Property<int?>("SequenceId")
                        .HasColumnType("int");

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<int?>("Spaces")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScaleId");

                    b.HasIndex("SequenceId");

                    b.HasIndex("SongId");

                    b.ToTable("Chords");
                });

            modelBuilder.Entity("MusicModels.Scale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Scales");
                });

            modelBuilder.Entity("MusicModels.Sequence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Length")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("Degree")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MajorOrMinor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScaleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UtubLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ScaleId");

                    b.HasIndex("UserId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("MusicModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("srcImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MusicModels.UserFavoriteSong", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SongId");

                    b.HasIndex("SongId");

                    b.ToTable("UserFavoriteSongs");
                });

            modelBuilder.Entity("MusicModels.WordLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineNumber")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.ToTable("WordLines");
                });

            modelBuilder.Entity("MusicModels.Chord", b =>
                {
                    b.HasOne("MusicModels.Scale", "Scale")
                        .WithMany("Chords")
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MusicModels.Sequence", "Sequence")
                        .WithMany("Chords")
                        .HasForeignKey("SequenceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("Chords")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Scale");

                    b.Navigation("Sequence");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.HasOne("MusicModels.Category", "Category")
                        .WithMany("Songs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.Scale", "Scale")
                        .WithMany()
                        .HasForeignKey("ScaleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MusicModels.User", "User")
                        .WithMany("MySongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("Scale");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.UserFavoriteSong", b =>
                {
                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("FavoritedByUsers")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MusicModels.User", "User")
                        .WithMany("FavoriteSongs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MusicModels.WordLine", b =>
                {
                    b.HasOne("MusicModels.Song", "Song")
                        .WithMany("WordLines")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("MusicModels.Category", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("MusicModels.Scale", b =>
                {
                    b.Navigation("Chords");
                });

            modelBuilder.Entity("MusicModels.Sequence", b =>
                {
                    b.Navigation("Chords");
                });

            modelBuilder.Entity("MusicModels.Song", b =>
                {
                    b.Navigation("Chords");

                    b.Navigation("FavoritedByUsers");

                    b.Navigation("WordLines");
                });

            modelBuilder.Entity("MusicModels.User", b =>
                {
                    b.Navigation("FavoriteSongs");

                    b.Navigation("MySongs");
                });
#pragma warning restore 612, 618
        }
    }
}
